version: '3'

services:
  webapp:
    image: humanconnection/frontend-nuxt:edge
    build:
      context: .
      args:
        BUILD_COMMIT: ${BUILD_COMMIT}
    stdin_open: true
    tty: true
    ports:
      - 172.17.0.1:3000:3000/tcp
