version: '3.5'

services:
  webapp:
    build:
      context: .
      args:
        BUILD_COMMIT: ${BUILD_COMMIT}
    environment:
      - NODE_ENV=development
    volumes:
      - .:/WebApp/
      - /WebApp/node_modules
    command: yarn run dev
    tty: true
